name: RyanJForth
favicon: null
layout_spectrum: 0.86092
typography_spectrum: 0.70718
title: Ryan J. Forth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#313640'
    - '#b35a26'
    - '#f68831'
    - '#a28659'
    - '#fdfffb'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
