name: RyanJForth
favicon: null
layout_spectrum: 0.857
typography_spectrum: 0.70718
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
  brandStrength: 0.75
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.25
purpose: []
