name: Ryan J. Forth
favicon: null
layout_spectrum: 0.4045
typography_spectrum: 0.811
title: Ryan J. Forth
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ff4917'
    - '#c29055'
    - '#5886fe'
    - '#ffffff'
    - '#fecb7e'
  brandStrength: 0.5
  lightness: 0.25
  saturation: 0
  rhythmicContrast: 0.5
purpose: []
